version: "3.8"  # If version is deprecated, you can remove it as per previous instructions.

services:
  # Node.js application service
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourFirstNameYourStudentNumber
      - POSTGRES_DB=labonedb
    depends_on:
      - db  # Make the server dependent on the db service being healthy

  # PostgreSQL database service
  db:
    image: postgres
    environment:
      - POSTGRES_DB=labonedb
      - POSTGRES_PASSWORD=YourFirstNameYourStudentNumber
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data  # Data persistence
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres  # Set the user to postgres

volumes:
  db-data:
